var dataLocalidades_arr= [
	{id:1, nombre: 'Usaquén (01)'},
	{id:2, nombre: 'Chapinero (02)'},
	{id:3, nombre: 'SantaFe (03)'},
	{id:4, nombre: 'San Cristóbal (04)'},
	{id:5, nombre: 'Usme (05)'},
	{id:6, nombre: 'Tunjuelito (06)'},
	{id:7, nombre: 'Bosa (07)'},
	{id:8, nombre: 'Kennedy (08)'},
	{id:9, nombre: 'Fontibón (09)'},
	{id:10, nombre: 'Engativá (10)'},
	{id:11, nombre: 'Suba (11)'},
	{id:12, nombre: 'Barrios Unidos (12)'},
	{id:13, nombre: 'Teusaquillo (13)'},
	{id:14, nombre: 'Los Mártires (14)'},
	{id:15, nombre: 'Antonio Nariño (15)'},
	{id:16, nombre: 'Puente Aranda (16)'},
	{id:17, nombre: 'La Candelaria (17)'},
	{id:18, nombre: 'Rafael Uribe Uribe (18)'},
	{id:19, nombre: 'Ciudad Bolívar (19)'},
	{id:20, nombre: 'Sumapaz (20)'}
];

var dataCategoria_arr = [
	{id:1, nombre: 'Musica'},
	{id:2, nombre: 'Teatro'},
	{id:3, nombre: 'Pintura'},
	{id:4, nombre: 'Fotografia'},
	{id:5, nombre: 'Social'}
];

var dataEventos_arr = [
	{
		eveid: 15, 
		evenom: 'Presentación opera de Berlin', 
		evecat_nom: 'Musica',
		evefecini: '25/11/2018 17:00', 
		evefecfin: '30/11/2018 19:30', 
		evedir: 'Teatro Nacional La Castellana: Calle 95 # 47-15 Barrio: La Castellana',
		eveubi: null,
		evetel: '321211211, 211212154',
		evedesc: 'Presentación de la opera de Berlin. Buses a todos los barrios.', 
		evevalor: '35,000.00', 
		eveobs: 'Mayores de 4 años pagan entrada', 
		eveurl: 'https://es.wikipedia.org/wiki/%C3%93pera_Alemana_de_Berl%C3%ADn',
		eveimgurl: 'https://cdn.pixabay.com/photo/2017/11/29/22/01/munich-2987186_960_720.jpg',
	},
	{
		eveid: 14, 
		evenom: 'Exposición fotografica Bogotana', 
		evecat_nom: 'Fotografia',
		evefecini: '15/11/2018 16:00', 
		evefecfin: '15/11/2018 20:30', 
		evedir: 'Museo Nacional: Calle # 15 ',
		eveubi: null,
		evetel: '211212154, 321211211',
		evedesc: 'Exposición fotografica de los barrrios mas antiguos de Bogota, a cargo de los profesionales xyz.', 
		evevalor: '0.00', 
		eveobs: '', 
		eveurl: 'http://www.museonacional.gov.co/Paginas/default.aspx',
		eveimgurl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Plaza_de_Toros_de_Bogot%C3%A1.JPG',
	},
	{
		eveid: 13, 
		evenom: 'Consurso de fotografia arquitectonica', 
		evecat_nom: 'Fotografia',
		evefecini: '15/11/2018 16:00', 
		evefecfin: '17/11/2018 20:30', 
		evedir: 'Centro de convenciones Gonzalo Jimenez de Quezada.',
		eveubi: null,
		evetel: '211212154, 321211211',
		evedesc: 'Exposición fotografica de los barrios mas antiguos de Bogota, a cargo de los profesionales xyz.', 
		evevalor: '0.00', 
		eveobs: '', 
		eveurl: 'http://kateringblue.co/centro-de-convenciones-eventos/',
		eveimgurl: 'https://upload.wikimedia.org/wikipedia/commons/2/25/Edificios_en_la_cra_7_con_clle_60_Bogot%C3%A1.JPG',
	},
	{
		eveid: 12, 
		evenom: 'Jornada de donación de libros', 
		evecat_nom: 'Social',
		evefecini: '14/11/2018 14:00', 
		evefecfin: '17/11/2018 20:00', 
		evedir: 'Biblioteca Luis Angel Arango',
		eveubi: null,
		evetel: '211212154, 321211211',
		evedesc: 'Se realizará una jornada de donación de libros para mejorar las condiciones de varias escuelas del sector', 
		evevalor: '0.00', 
		eveobs: '', 
		eveurl: 'http://www.banrepcultural.org/bogota/biblioteca-luis-angel-arango',
		eveimgurl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Cerros_desde_CCGGM.jpg',
	},
	{
		eveid: 12, 
		evenom: 'Boogie Nigths', 
		evecat_nom: 'Musica',
		evefecini: '07/11/2018 18:00', 
		evefecfin: '08/11/2018 05:00', 
		evedir: 'MoviStar Arena: Cra. 30 # ',
		eveubi: null,
		evetel: '321211211',
		evedesc: 'Fiesta tematica disco con la mejor musica de los 70s', 
		evevalor: '77,000.00', 
		eveobs: 'Se requiere usar ropa de la epoca.', 
		eveurl: 'https://www.movistararena.co/MovistarArena/',
		eveimgurl: 'https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2F736x%2F36%2F7a%2Fd6%2F367ad66d1eca8c5c7d568ebd9967206b--saturday-night-fever-s-party.jpg&f=1',
	},
];

	
